AWSTemplateFormatVersion: '2010-09-09'
Description: world happiness infra resources
Resources:
  MyRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "world-happiness-api"