AWSTemplateFormatVersion: '2010-09-09'
Description: world happiness infra resources
Parameters:
  ApiVersion:
    Type: String
    Description: "api version"
    Default: "v1"
  CognitoDomain:
    Type: String
    MinLength: 3
    MaxLength: 63
    AllowedPattern: ^[a-z0-9](?:[a-z0-9\-]{0,61}[a-z0-9])?$
    Description: Enter a string. Must be alpha numeric 3-63 in length.
    Default: "world-happiness"
Resources:
  MyRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "world-happiness-api"
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UsernameConfiguration:
        CaseSensitive: true
      AutoVerifiedAttributes:
        - email
      UserPoolName: !Sub ${CognitoDomain}-user-pool
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      AllowedOAuthFlowsUserPoolClient: true
      GenerateSecret: true
      CallbackURLs:
        - https://api.worldhappiness.beyondgdp.co.uk
      AllowedOAuthFlows:
        - implicit
      AllowedOAuthScopes:
        - phone
        - email
        - openid
        - profile
      SupportedIdentityProviders:
        - COGNITO
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref CognitoDomain
      UserPoolId: !Ref UserPool
  ApiGatewayVpcLink:
    Type: AWS::ApiGateway::VpcLink
    Properties:
      Description: "worldhappiness vpc link"
      Name: "worldhappinessVpcLink"
      TargetArns:
        - arn:aws:elasticloadbalancing:eu-west-1:436139220509:loadbalancer/net/a105223b23e154a86b9d7f8fc10a493b/de4ae8c2399c8471
  ApiGatewayAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    DependsOn:
      ApiGateway
    Properties:
      IdentitySource: method.request.header.authorization
      Name: Cognito
      ProviderARNs:
        - "arn:aws:cognito-idp:eu-west-1:436139220509:userpool/eu-west-1_pt0xIJIEc"
      RestApiId: !Ref ApiGateway
      Type: COGNITO_USER_POOLS
  ApiGatewayDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: !Ref ApiVersion
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: world happiness api gateway
      EndpointConfiguration:
        Types:
          - REGIONAL
      Name: "world-happiness-gateway"
      Body:
        openapi: "3.0.1"
        info:
          title: "world-happiness-gateway"
          description: "world happiness api gateway"
          version: "v1"
        servers:
          - url: "https://l84n6w2qs6.execute-api.eu-west-1.amazonaws.com/{basePath}"
            variables:
              basePath:
                default: "/prod"
        paths:
          /countries/{countryName}:
            get:
              parameters:
                - name: "countryName"
                  in: "path"
                  required: true
                  schema:
                    type: "string"
              responses:
                "404":
                  description: "404 response"
                  content: { }
                "200":
                  description: "200 response"
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/Country"
                "401":
                  description: "401 response"
                  content: { }
                "403":
                  description: "403 response"
                  content: { }
              security:
                - Cognito: [ ]
              x-amazon-apigateway-integration:
                type: "http_proxy"
                connectionId: "${stageVariables.vpcLinkId}"
                httpMethod: "GET"
                uri: "http://a105223b23e154a86b9d7f8fc10a493b-de4ae8c2399c8471.elb.eu-west-1.amazonaws.com/countries/{countryName}"
                responses:
                  default:
                    statusCode: "200"
                connectionType: "VPC_LINK"
                requestParameters:
                  integration.request.path.countryName: "method.request.path.countryName"
                passthroughBehavior: "when_no_match"
          /countries:
            get:
              responses:
                "401":
                  description: "401 response"
                  content: { }
                "200":
                  description: "200 response"
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/Countries"
                "403":
                  description: "403 response"
                  content: { }
              security:
                - Cognito: [ ]
              x-amazon-apigateway-integration:
                type: "http_proxy"
                connectionId: "${stageVariables.vpcLinkId}"
                httpMethod: "GET"
                uri: "http://a105223b23e154a86b9d7f8fc10a493b-de4ae8c2399c8471.elb.eu-west-1.amazonaws.com/countries"
                responses:
                  default:
                    statusCode: "200"
                passthroughBehavior: "when_no_match"
                connectionType: "VPC_LINK"
        components:
          schemas:
            Countries:
              type: "array"
              description: "list of happiness country data"
              items:
                $ref: "#/components/schemas/Country"
            Country:
              type: "object"
              properties:
                score:
                  type: "number"
                name:
                  type: "string"
          securitySchemes:
            Cognito:
              type: "apiKey"
              name: "authorization"
              in: "header"
              x-amazon-apigateway-authtype: "cognito_user_pools"
              x-amazon-apigateway-authorizer:
                type: "cognito_user_pools"
                providerARNs:
                  - "arn:aws:cognito-idp:eu-west-1:436139220509:userpool/eu-west-1_pt0xIJIEc"

  Dashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: "worldhappiness"
      DashboardBody: |-
        {
            "widgets": [
                {
                    "type": "metric",
                    "x": 0,
                    "y": 0,
                    "width": 12,
                    "height": 4,
                    "properties": {
                        "metrics": [
                            [ "AWS/ELB", "RequestCount", "LoadBalancerName", "af31af20b0e3642c889cc73bb0814b81", { "period": 300, "stat": "Sum" } ]
                        ],
                        "legend": {
                            "position": "bottom"
                        },
                        "region": "eu-west-1",
                        "liveData": false,
                        "title": "RequestCount: Sum"
                    }
                },
                {
                    "type": "metric",
                    "x": 12,
                    "y": 0,
                    "width": 12,
                    "height": 4,
                    "properties": {
                        "metrics": [
                            [ "AWS/ELB", "Latency", "LoadBalancerName", "af31af20b0e3642c889cc73bb0814b81", { "period": 300, "stat": "Average" } ]
                        ],
                        "legend": {
                            "position": "bottom"
                        },
                        "region": "eu-west-1",
                        "liveData": false,
                        "title": "Latency: Average"
                    }
                },
                {
                    "type": "metric",
                    "x": 0,
                    "y": 4,
                    "width": 8,
                    "height": 4,
                    "properties": {
                        "metrics": [
                            [ "AWS/ELB", "BackendConnectionErrors", "LoadBalancerName", "af31af20b0e3642c889cc73bb0814b81", { "period": 300, "stat": "Sum" } ]
                        ],
                        "legend": {
                            "position": "bottom"
                        },
                        "region": "eu-west-1",
                        "liveData": false,
                        "title": "BackendConnectionErrors: Sum"
                    }
                },
                {
                    "type": "metric",
                    "x": 8,
                    "y": 4,
                    "width": 8,
                    "height": 4,
                    "properties": {
                        "metrics": [
                            [ "AWS/ELB", "SpilloverCount", "LoadBalancerName", "af31af20b0e3642c889cc73bb0814b81", { "period": 300, "stat": "Sum" } ]
                        ],
                        "legend": {
                            "position": "bottom"
                        },
                        "region": "eu-west-1",
                        "liveData": false,
                        "title": "SpilloverCount: Sum"
                    }
                },
                {
                    "type": "metric",
                    "x": 16,
                    "y": 4,
                    "width": 8,
                    "height": 4,
                    "properties": {
                        "metrics": [
                            [ "AWS/ELB", "SurgeQueueLength", "LoadBalancerName", "af31af20b0e3642c889cc73bb0814b81", { "period": 300, "stat": "Average" } ]
                        ],
                        "legend": {
                            "position": "bottom"
                        },
                        "region": "eu-west-1",
                        "liveData": false,
                        "title": "SurgeQueueLength: Average"
                    }
                },
                {
                    "type": "metric",
                    "x": 0,
                    "y": 8,
                    "width": 8,
                    "height": 4,
                    "properties": {
                        "metrics": [
                            [ "AWS/ELB", "HealthyHostCount", "LoadBalancerName", "af31af20b0e3642c889cc73bb0814b81", { "period": 300, "stat": "Average" } ]
                        ],
                        "legend": {
                            "position": "bottom"
                        },
                        "region": "eu-west-1",
                        "liveData": false,
                        "title": "HealthyHostCount: Average"
                    }
                },
                {
                    "type": "metric",
                    "x": 8,
                    "y": 8,
                    "width": 8,
                    "height": 4,
                    "properties": {
                        "metrics": [
                            [ "AWS/ELB", "UnHealthyHostCount", "LoadBalancerName", "af31af20b0e3642c889cc73bb0814b81", { "period": 300, "stat": "Average" } ]
                        ],
                        "legend": {
                            "position": "bottom"
                        },
                        "region": "eu-west-1",
                        "liveData": false,
                        "title": "UnHealthyHostCount: Average"
                    }
                },
                {
                    "type": "metric",
                    "x": 16,
                    "y": 8,
                    "width": 8,
                    "height": 4,
                    "properties": {
                        "metrics": [
                            [ "AWS/ELB", "HTTPCode_Backend_2XX", "LoadBalancerName", "af31af20b0e3642c889cc73bb0814b81", { "period": 300, "stat": "Sum" } ]
                        ],
                        "legend": {
                            "position": "bottom"
                        },
                        "region": "eu-west-1",
                        "liveData": false,
                        "title": "HTTPCode_Backend_2XX: Sum"
                    }
                },
                {
                    "type": "metric",
                    "x": 0,
                    "y": 12,
                    "width": 8,
                    "height": 4,
                    "properties": {
                        "metrics": [
                            [ "AWS/ELB", "HTTPCode_Backend_3XX", "LoadBalancerName", "af31af20b0e3642c889cc73bb0814b81", { "period": 300, "stat": "Sum" } ]
                        ],
                        "legend": {
                            "position": "bottom"
                        },
                        "region": "eu-west-1",
                        "liveData": false,
                        "title": "HTTPCode_Backend_3XX: Sum"
                    }
                },
                {
                    "type": "metric",
                    "x": 8,
                    "y": 12,
                    "width": 8,
                    "height": 4,
                    "properties": {
                        "metrics": [
                            [ "AWS/ELB", "HTTPCode_Backend_4XX", "LoadBalancerName", "af31af20b0e3642c889cc73bb0814b81", { "period": 300, "stat": "Sum" } ]
                        ],
                        "legend": {
                            "position": "bottom"
                        },
                        "region": "eu-west-1",
                        "liveData": false,
                        "title": "HTTPCode_Backend_4XX: Sum"
                    }
                },
                {
                    "type": "metric",
                    "x": 16,
                    "y": 12,
                    "width": 8,
                    "height": 4,
                    "properties": {
                        "metrics": [
                            [ "AWS/ELB", "HTTPCode_Backend_5XX", "LoadBalancerName", "af31af20b0e3642c889cc73bb0814b81", { "period": 300, "stat": "Sum" } ]
                        ],
                        "legend": {
                            "position": "bottom"
                        },
                        "region": "eu-west-1",
                        "liveData": false,
                        "title": "HTTPCode_Backend_5XX: Sum"
                    }
                }
            ]
        }